language: objective-c

xcode_project: Solar.xcodeproj
xcode_scheme: SolarTests
xcode_sdk: iphonesimulator14.2
osx_image: xcode12.2

script:
  - xcodebuild clean build -project Solar.xcodeproj -scheme 'Solar iOS' -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4'
  - travis_retry xcodebuild test -project Solar.xcodeproj -scheme 'Solar iOS' -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4'
